bumerang/apps/news/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from bumerang.apps.news.views import NewsListView, NewsItemDetailView


urlpatterns = patterns('',
    url(r'^$',
        NewsListView.as_view(),
        name='news-list'
    ),
    url(r'^(?P<category>[-\w]+)/$',
        NewsListView.as_view(),
        name='news-list-category'
    ),
    url(r'^(?P<category>[-\w]+)/(?P<slug>[-\w]+)/$',
        NewsItemDetailView.as_view(),
        name='news-detail'
    ),
)

bumerang/apps/photo/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from bumerang.apps.photo.albums.views import PhotoAlbumDetailView, \
    PhotoAlbumListView
from bumerang.apps.photo.views import increase_views_count

from bumerang.apps.utils.views import ObjectsDeleteView
from models import Photo
from albums.models import PhotoAlbum
from views import (PhotoListView, PhotoCreateView, PhotoDetailView,
    PhotoUpdateView, PhotoMoveView)
from albums.views import (PhotoAlbumCreateView, PhotoSetCoverView,
    PhotoAlbumUpdateView)


urlpatterns = patterns('',
    url(r'^album/add/$',
        login_required(PhotoAlbumCreateView.as_view()),
        name='photo-album-add'
    ),
    url(r'^album(?P<photo_album_id>[\d]+)/add/$',
        login_required(PhotoCreateView.as_view()),
        name='album-photo-add'
    ),
    url(r'^album(?P<pk>[\d]+)/$',
        PhotoAlbumDetailView.as_view(),
        name='photo-album-detail'
    ),
    url(r'^album(?P<pk>[\d]+)/edit/$',
        login_required(PhotoAlbumUpdateView.as_view()),
        name='photo-album-edit'
    ),
    url(r'^album(?P<pk>[\d]+)/set-cover/$',
        login_required(PhotoSetCoverView.as_view()),
        name='photo-album-cover'
    ),
    url(r'^add/$',
        login_required(PhotoCreateView.as_view()),
        name='photo-add'
    ),
    url(r'^(?P<pk>[\d]+)/edit/$',
        login_required(PhotoUpdateView.as_view()),
        name='photo-edit'
    ),
    url(r'^$',
        PhotoAlbumListView.as_view(),
        name='photo-list'
    ),
    url(r'^~(?P<category>[\w\-]+)/$',
        PhotoAlbumListView.as_view(),
        name='photo-list-category'
    ),
    url(r'^photos-delete/$',
        login_required(ObjectsDeleteView.as_view(model=Photo)),
        name='photos-delete'
    ),
    url(r'^albums-delete/$',
        login_required(ObjectsDeleteView.as_view(model=PhotoAlbum)),
        name='photoalbums-delete'
    ),
    url(r'^photo-move/$',
        login_required(PhotoMoveView.as_view()),
        name='photo-move'
    ),
    url(r'^(?P<pk>\w+)/$',
        PhotoDetailView.as_view(),
        name='photo-detail'
    ),

    url(r'^(?P<pk>[\d]+)/update-count/$',
        increase_views_count,
        name='photo-update-count'
    ),

    url(r'^~(?P<category>[\w\-]+)/$',
        PhotoAlbumListView.as_view(),
        name='photo-list-category'
    ),
)

bumerang/apps/video/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from bumerang.apps.utils.views import (
    XMLDetailView, ObjectsDeleteView, AjaxRatingView)
from .albums.models import VideoAlbum
from .albums.views import (
    VideoAlbumCreateView, VideoSetCoverView, VideoAlbumUpdateView,
    VideoAlbumDetailView)
from .views import (
    VideoListView, VideoCreateView, VideoDetailView, VideoUpdateView,
    VideoMoveView, endpoint, StreamCreateAjaxView, VideoListAjaxView,
    VideoGetS3UploadURLView)
from .models import Video


urlpatterns = patterns(
    '',
    url(r'^$',
        VideoListView.as_view(),
        name='video-list'),

    url(r'^endpoint$',
        endpoint,
        name='video-endpoint'),

    url(r'^~(?P<category>[\w\-]+)/$',
        VideoListView.as_view(),
        name='video-list-category'),

    url(r'^ajax/stream-add/$',
        login_required(StreamCreateAjaxView.as_view()),
        name='stream-create'),

    # AJAX video list
    url(r'^ajax/(?P<category>[\w\-]+)/$',
        VideoListAjaxView.as_view(),
        name='video-list-ajax'),

    url(r'^album/add/$',
        login_required(VideoAlbumCreateView.as_view()),
        name='video-album-add'),

    url(r'^album(?P<video_album_id>[\d]+)/add/$',
        login_required(VideoCreateView.as_view()),
        name='album-video-add'),

    url(r'^album(?P<pk>[\d]+)/$',
        VideoAlbumDetailView.as_view(),
        name='video-album-detail'),

    url(r'^album(?P<pk>[\d]+)/edit/$',
        login_required(VideoAlbumUpdateView.as_view()),
        name='video-album-edit'),

    url(r'^album(?P<pk>[\d]+)/set-cover/$',
        login_required(VideoSetCoverView.as_view()),
        name='video-album-cover'),

    url(r'^add/$',
        login_required(VideoCreateView.as_view()),
        name='video-add'),

    url(r'^(?P<pk>[\d]+)/edit/$',
        login_required(VideoUpdateView.as_view()),
        name='video-edit'),

    url(r'^(?P<pk>[\d]+)/get-s3-upload-url/$',
        login_required(VideoGetS3UploadURLView.as_view()),
        name='video-get-s3-upload-url'),

    url(r'^videos-delete/$',
        login_required(ObjectsDeleteView.as_view(model=Video)),
        name='videos-delete'),

    url(r'^albums-delete/$',
        login_required(ObjectsDeleteView.as_view(model=VideoAlbum)),
        name='videoalbums-delete'),

    url(r'^video-move/$',
        login_required(VideoMoveView.as_view()),
        name='video-move'),

    url(r'^(?P<pk>\w+).xml$',
        XMLDetailView.as_view(
            model=Video, template_name_suffix='_xml'),
        name='video-xml'),

    # Ratings
    url(r'^rate/(?P<object_id>\d+)/(?P<score>\d+)/$',
        login_required(AjaxRatingView()), {
            'app_label': 'video',
            'model': 'video',
            'field_name': 'rating',
        },
        name='video-rate'),

    url(r'^(?P<pk>\w+)/$',
        VideoDetailView.as_view(),
        name='video-detail'),
)

bumerang/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from filebrowser.sites import FileBrowserSite

from bumerang.apps.utils.media_storage import media_storage


site = FileBrowserSite(name='filebrowser', storage=media_storage)

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^feedback/', include('bumerang.apps.feedback.urls')),
    (r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    (r'^tinymce/', include('tinymce.urls')),
    url(r'^$', include('bumerang.apps.bumerang_site.urls')),
    url(r'^news/', include('bumerang.apps.news.urls')),
    url(r'^accounts/', include('bumerang.apps.accounts.urls')),
    url(r'^advices/', include('bumerang.apps.advices.urls')),
    url(r'^video/', include('bumerang.apps.video.urls')),
    url(r'^photo/', include('bumerang.apps.photo.urls')),
    url(r'^playlists/', include('bumerang.apps.video.playlists.urls')),
    url(r'^events/', include('bumerang.apps.events.urls')),
    url(r'^projects/', include('bumerang.apps.projects.urls')),
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bumerang/apps/advices/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from mptt.models import MPTTModel, TreeForeignKey


class Advice(MPTTModel):
    name = models.CharField(max_length=255, unique=True)
    parent = TreeForeignKey('self', null=True, blank=True,
                            related_name='children')
    description = models.TextField(
        u'Описание раздела', default=u'Введите описание')
    # Slug of node's name
    slug = models.SlugField()
    # Url hash
    url = models.CharField(max_length=1024, editable=False)
    # TODO: remove sort_order field
    sort_order = models.IntegerField(default=0, verbose_name=u'Позиция')

    def get_absolute_url(self):
        return '/advices/%s/' % self.url

    def __unicode__(self):
        return u'{0}'.format(self.name)

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        verbose_name, verbose_name_plural = u'Совет', u'Советы'


@receiver(pre_save, sender=Advice)
def advice_pre_save(sender, **kwargs):
    advice = kwargs['instance']
    # Building advice URL from parents
    advice.url = u'/'.join(advice.get_ancestors(
        include_self=True).values_list('slug', flat=True))

bumerang/apps/banners/models.py
# -*- coding: utf-8 -*-
from random import randint

from django.db import models

from bumerang.apps.utils.models import FileModelMixin, nullable
from bumerang.apps.utils.media_storage import media_storage


class BannerBase(FileModelMixin, models.Model):
    name = models.CharField(max_length=255, verbose_name=u'название')
    url = models.URLField(
        verbose_name=u'Ссылка', help_text=u'Заполняется, если баннер не flash',
        **nullable)
    alt = models.CharField(
        max_length=65, verbose_name=u'Описание изображения',
        help_text=u'Заполняется, если баннер не flash', **nullable)
    image = models.ImageField(
        u'изображение', storage=media_storage, upload_to='bs',
        help_text=u'Заполняется, если баннер не flash', **nullable)
    flash = models.FileField(
        u'flash-баннер', storage=media_storage, upload_to='bs',
        help_text=u'заполняется, если это flash-баннер', **nullable)
    is_active = models.BooleanField(u'Активен', default=True)
    create_date = models.DateTimeField(u'Дата создания', auto_now_add=True)

    class Meta:
        abstract = True

    def __unicode__(self):
        if self.image:
            return u"""
    <p>
        <a href="{0}">
            <img src="{1}" alt="{2}" width="200" height="340" />
        </a>
    </p>
        """.format(self.url, self.image.url, self.alt)
        return u"""
  <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"
   width="200" height="340">
    <param name="movie" value="{0}" />
    <!--[if !IE]>-->
    <object type="application/x-shockwave-flash" data="{0}"
     width="200" height="340">
    <!--<![endif]-->
    <!--[if !IE]>-->
    </object>
    <!--<![endif]-->
  </object>
        """.format(self.flash)


class HeadBanner(FileModelMixin, models.Model):
    name = models.CharField(max_length=255, verbose_name=u'Название')
    url = models.URLField(verbose_name=u'Ссылка')
    text = models.CharField(max_length=255, verbose_name=u'Текст ссылки')
    background_image = models.ImageField(
        u'Подложка', storage=media_storage, upload_to='headbs')
    is_active = models.BooleanField(default=True)
    create_date = models.DateTimeField(u'Дата создания', auto_now_add=True)

    def __unicode__(self):
        return u'{0}'.format(self.name)

    class Meta:
        verbose_name = u'Баннер в шапке'
        verbose_name_plural = u'Баннеры в шапке'


class MainPageBanner(BannerBase):
    weight = models.IntegerField(u'Вес баннера')

    class Meta:
        verbose_name = u'Баннер главной страницы'
        verbose_name_plural = u'Баннеры главной страницы'

    @classmethod
    def get_some(cls):
        banners = cls.objects.filter(is_active=True)
        if not banners.exists():
            return None
        random_number = randint(1, sum(banner.weight for banner in banners))
        weight = 0
        for banner in banners:
            weight += banner.weight
            if weight > random_number:
                return banner


class EventBanner(BannerBase):
    event = models.ForeignKey('events.Event')

    class Meta:
        verbose_name = u'Баннер события'
        verbose_name_plural = u'Баннеры событий'


class CrossSiteBanner(BannerBase):
    POSITION_CHOICES = (
        (1, 1),
        (2, 2),
        (3, 3)
    )
    position = models.IntegerField(u'Позиция', choices=POSITION_CHOICES)

    class Meta:
        verbose_name = u'Сквозной баннер'
        verbose_name_plural = u'Сквозные баннеры'


class BumTVBanner(BannerBase):
    sort_order = models.PositiveSmallIntegerField(
        u'Порядок сортировки', **nullable)

    class Meta:
        verbose_name = u'Баннер 240x124'
        verbose_name_plural = u'Баннеры 240x124'
        ordering = ['-sort_order', '-id']

    def __unicode__(self):
        if self.image:
            return u"""
                <p>
                    <a href="{0}">
                        <img src="{1}" alt="{2}" width="240" height="124" />
                    </a>
                </p>
                    """.format(self.url, self.image.url, self.alt)
        return u"""
          <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"
           width="240" height="124">
            <param name="movie" value="{0}" />
            <!--[if !IE]>-->
            <object type="application/x-shockwave-flash" data="{0}"
             width="240" height="124">
            <!--<![endif]-->
            <!--[if !IE]>-->
            </object>
            <!--<![endif]-->
          </object>
                """.format(self.flash)

bumerang/apps/bumerang_site/models.py
from django.db import models

bumerang/apps/feedback/models.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.core.mail import EmailMessage
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Feedback(models.Model):
    subject = models.CharField(max_length=100, verbose_name=_('Subject'))
    name = models.CharField(max_length=100, verbose_name=_('Name'))
    email = models.EmailField(verbose_name=_('Email'))
    message = models.TextField(verbose_name=_('Message'))
    time = models.DateTimeField(auto_now_add=True, verbose_name=_('Time'))
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('User'),
                             null=True, blank=True, default=None)

    class Meta:
        ordering = ['-time']

    def __unicode__(self):
        return self.message

    def save(self, *args, **kwargs):
        super(Feedback, self).save(*args, **kwargs)
        message = u"""
        От {0}
        
        Тема:
        {1}
        
        Сообщение:
        {2}
        """.format(self.name, self.subject, self.message)
        mail = EmailMessage(
            '%s%s' % (settings.EMAIL_SUBJECT_PREFIX, self.subject),
            message, settings.SERVER_EMAIL, [a[1] for a in settings.MANAGERS],
            headers={'Reply-To': self.email})
        mail.send(fail_silently=False)

bumerang/apps/projects/models.py
# -*- coding: utf-8 -*-
from django.core.urlresolvers import reverse
from django.db import models

from bumerang.apps.utils.media_storage import media_storage
from bumerang.apps.utils.models import FileModelMixin, nullable


class Project(FileModelMixin, models.Model):
    title = models.CharField(max_length=255, verbose_name=u'Название')
    text = models.TextField(verbose_name=u'Описание проекта')
    image = models.ImageField(
        u'Изображение', storage=media_storage, upload_to='projects',
        help_text=u'Пропорции изображения - 11x3, минимальная и желательная '
                  u'ширина изображения - 220px. Обязательно соблюдайте эти '
                  u'параметры, иначе верстка на главной странице поплывет',
        **nullable)

    videos = models.ManyToManyField(
        'video.Video', verbose_name=u'Видео проекта')

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = u'Проект'
        verbose_name_plural = u'Проекты'

    def get_absolute_url(self):
        return reverse('project-detail', args=[self.pk])

bumerang/apps/video/albums/models.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.db import models
from django.db.models import Max
from django.core.urlresolvers import reverse

from bumerang.apps.utils.models import TitleUnicode, nullable
from bumerang.apps.utils.media_storage import media_storage
from bumerang.apps.video.models import Video


def video_album_preview_upload_to(instance, filename):
    return 'previews/video-album/{0}/{1}'.format(instance.owner.slug, filename)


class VideoAlbum(models.Model, TitleUnicode):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(u'Название', max_length=100)
    description = models.TextField(u'Описание', **nullable)
    created = models.DateTimeField(
        u'Дата создания', auto_now_add=True, **nullable)
    image = models.ImageField(
        u'Обложка', storage=media_storage,
        upload_to=video_album_preview_upload_to, **nullable)
    cover = models.ForeignKey(Video, on_delete=models.SET_NULL, **nullable)

    class Meta:
        verbose_name = u'Видеоальбом'
        verbose_name_plural = u'Видеоальбомы'

    def get_absolute_url(self):
        return reverse('video-album-detail', args=(self.id,))
    get_absolute_url.short_description = u'Ссылка на страницу видеоальбома'

    def last_update(self):
        return self.video_set.all().aggregate(Max('created'))['created__max']
    last_update.short_description = u'Последнее видео добавлено'

    def preview(self):
        if self.image:
            return self.image
        elif self.cover:
            if self.cover.preview():
                return self.cover.preview().thumbnail
        return None

bumerang/apps/feedback/forms.py
from django import forms

from .models import Feedback


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        exclude = ('user', 'time')

bumerang/templates/video/video_edit_form.html
{% extends "video/tabs_wrapper.html" %}
{% load sitetree %}
{% load rupluralize %}
{% load videotags %}


{% block left_column %}
    <div class="b-tabs d-sh">
        <dl>
            {% include 'snippets/menu.html' with selected='video' %}
            <dd class="selected"><div class="b-tabs__tab-content">
                <section class="b-profile">
                    <header class="b-profile__head b-profile__head_small cleared">
                        <div class="b-profile__pic">
                            <div class="b-ava b-ava_small">
                                {% if object.owner.min_avatar %}
                                    <img src="{{ object.owner.min_avatar.url }}" width="60" height="60" alt="" />
                                {% else %}
                                    <img src="{{ STATIC_URL }}i/noava.jpg" width="60" height="60" alt="" />
                                {% endif %}
                                <i class="b-ava__sh"></i>
                            </div>
                        </div>
                        <div class="b-profile__txt">
                            {% if user.id == object.owner_id %}
                                <ul class="b-service-buttons">
                                    <li class="edit"><i></i><a href="{% url 'profile-edit' %}">Редактировать профиль</a></li>
                                </ul>
                            {% endif %}
                            <a href="{% url 'profile-detail' object.owner_id %}">
                                <h4>{{ object.owner.title }}</h4>
                            </a>
                            <p>{{ object.owner.place }}</p>
                        </div>
                    </header>
                </section>
                <div class="b-hr"><hr /></div>
                <header class="b-head cleared">
                    <ul class="b-service-buttons">
                        <li class="addphoto"><i></i><a href="">Добавить фото</a></li>
                        <li class="edit"><i></i><a href="">Редактировать альбом</a></li>
                    </ul>
                    <a href="" class="b-button-prev"><span>Все альбомы</span></a>
                    <h3>
                        Редактирование видео &laquo;{{ form.instance.title }}&raquo;
                    </h3>
                </header>
                <section class="b-form b-form_smaller b-form_edit">
                    <form name="videoform" action="{% url 'video-edit' form.instance.id %}" method="post">
                        {% csrf_token %}
                        <div class="b-form__fields">
                            {% for item in form %}
                                <fieldset>
                                    <div class="b-form__field">
                                        <label>
                                            <span class="f-title">
                                                <span>{{ item.label }}</span>
                                            </span>
                                            <span class="f-input">
                                                {{ item }}
                                            </span>
                                        </label>
                                        {% if item.errors %}
                                            <div class="f-err"><span>{{ item.errors }}</span></div>
                                        {% endif %}
                                    </div>
                                </fieldset>
                            {% endfor %}
                        </div>
                        <footer class="b-form__footer">
                            <div class="wrap">
                                <a class="b-button b-button_yellow button-submit">Сохранить</a>
                            </div>
                        </footer>
                    </form>
                </section>
            </div></dd>

        </dl>
    </div>
{% endblock %}

{% block popup %}
    <section class="b-popup" id="popup-del-video" style="left:50%; top:100px;">
        <section class="b-form b-form_left b-form_smaller b-form_popup b-form_popup_confirm">
            <header class="b-form__header">
                <h4>
                    Вы дйствительно хотите удалить видеозапись?
                </h4>
                <p>
                    Видео будет удалено безвозвратно.
                </p>
            </header>
            <footer class="b-form__footer cleared">
                <a class="b-button b-button_yellow left cancel">Отменить</a>
                <a class="b-button b-button_red right videos_delete">Удалить</a>
            </footer>
        </section><!--b-form-->
        <div class="b-popup__tl"></div>
        <div class="b-popup__tr"></div>
        <div class="b-popup__br"></div>
        <div class="b-popup__bl"></div>
    </section><!--b-popup-->

    <section class="b-popup" id="popup-move-video" style="left:50%; top:100px;">
        <section class="b-form b-form_smaller b-form_popup">
            <header class="b-form__header">
                <h3>
                    Переместить в альбом
                </h3>
            </header>
            <div class="b-form__fields">
                <div class="b-form__field">
                    {% for item in object.owner.videoalbum_set.all %}
                        <div class="b-form__field b-form__field_radio">
                            <div class="f-radio">
                                <div>
                                    <input {% if item == object %}disabled="disabled"{% endif %} type="radio" name="album" value="{{ item.id }}" id="album{{ item.id }}" />
                                    <label for="album{{ item.id }}" {% if item == object %}style="color: #666;"{% endif %}>
                                        {{ item.title }}
                                        {% if item == object %}(Текущий альбом){% endif %}
                                    </label>
                                </div>
                                <div class="f-err"><span></span></div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <footer class="b-form__footer">
                <div class="wrap">
                    <a href="" class="b-button b-button_yellow videos_move button-submit">Переместить</a>
                </div>
                <div class="clear"></div>
            </footer>
        </section><!--b-form-->
        <div class="b-popup__close" title="Закрыть"><i class="b-ico b-ico_x"><i></i></i></div>
        <div class="b-popup__tl"></div>
        <div class="b-popup__tr"></div>
        <div class="b-popup__br"></div>
        <div class="b-popup__bl"></div>
    </section><!--b-popup-->

    <section class="b-popup" id="popup-edit-video" style="left:50%; top:100px;">
        <section class="b-form b-form_smaller b-form_popup">
            <header class="b-form__header">
                <h3>
                    Редактирование видео
                </h3>
            </header>
            <div class="b-form__fields">
                <div class="b-form__field">
                    <label>
                        <span class="f-title"><span>Название</span></span>
					<span class="f-input">
						<input type="text" value="" class="wide" />
					</span>
                    </label>
                </div>
                <div class="b-form__field">
                    <label>
                        <span class="f-title"><span>Описание</span></span>
					<span class="f-textarea">
						<textarea rows="5" cols="45" class="wide wide_descr3"></textarea>
					</span>
                    </label>
                </div>
            </div>
            <footer class="b-form__footer">
                <div class="wrap">
                    <div class="hint"><small>Осталось заполнить: название</small></div>
                    <a href="" class="b-button b-button_yellow disabled">Создать</a>
                </div>
                <span class="or">или <a href="" class="b-pseudolink">отменить</a> и вернуться к альбомам.</span>
                <div class="clear"></div>
            </footer>
        </section><!--b-form-->
        <div class="b-popup__close" title="Закрыть"><i class="b-ico b-ico_x"><i></i></i></div>
        <div class="b-popup__tl"></div>
        <div class="b-popup__tr"></div>
        <div class="b-popup__br"></div>
        <div class="b-popup__bl"></div>
    </section><!--b-popup-->
{% endblock %}